// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel AddVelocity

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> ResultingVelocity;
RWTexture2D<float4> Velocity;
int X;
int Y;
float AmountX;
float AmountY;

[numthreads(1, 1, 1)]
void AddVelocity (uint3 id : SV_DispatchThreadID)
{
    // Only update the specific texel at (X, Y)

        ResultingVelocity[id.xy] = float4(AmountX, AmountY, 0, 1.0f);
}